name: Weekly Conference Sort Update

on:
  schedule:
  # Runs at 00:00 UTC on Friday
  # https://crontab.guru/#0_0_*_*_6
  - cron: '0 0 * * 6'
  # Optional: Allow manual triggering
  workflow_dispatch:


jobs:
  update-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.4

    - name: Run links command
      run: pixi run sort

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      id: create_pr
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: 'chore: sort conferences'
        title: 'chore: sort conferences'
        body: |
          Automated PR to update conference.

          This PR was automatically generated by the Update workflow.
        branch: automated/sort-conferences
        delete-branch: true

    - name: Auto merge
      if: steps.create_pr.outputs.pull-request-operation == 'created'
      run: gh pr merge --merge --auto "${{ steps.create_pr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
